line: kodo
limit: 3
streamers:
  /home/jh/Downloads/blive/Videos/1234567/%P:
    copyright: 1
    source: https://live.bilibili.com/1234567
    tid: 138
    cover: 
    title: 【弹幕版】XXX直播回放-%Y年%M月%d日%H点场
    desc_format_id: 0
    desc: your video description
    dynamic: ""
    tag: tag1,tag2,tag3
    dtime: ~
