ARG CUDA_VERSION=12.2
FROM nvidia/cuda:${CUDA_VERSION}.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    python3.10-venv \
    ffmpeg \
    git \
    gcc \
    procps \
    lsof \
    curl \
    vim \
    fonts-noto-cjk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# using python3.10 since numba is not compatible with higher python versions
RUN ln -sf /usr/bin/python3.10 /usr/bin/python3 && \
ln -sf /usr/bin/python3 /usr/bin/python && \
python -m pip install --upgrade pip

RUN git clone https://github.com/timerring/bilive /app

RUN touch src/utils/cookies.json


RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir Videos


ENV BILIVE_PATH=/app

COPY entrypoint-gpu.sh /entrypoint-gpu.sh
RUN chmod +x /entrypoint-gpu.sh

EXPOSE 2233
VOLUME /app

ENTRYPOINT ["/entrypoint-gpu.sh"]
