services:
  bilive:
    #build: .
    #user: "1001:1001"
    image: bilive-gpu:latest
    ports:
      - "65004:2233"
    volumes:
      - ./subtitle_models:/app/src/subtitle/models
      - ./logs:/app/logs
      - ./config:/app/config
    network_mode: bridge
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Fill numbers if you don't want to use all GPUs
              capabilities: [gpu, utility, compute, video] # Ensure GPU capability, don't change
