version = "1.0"
webhooks = []

[[tasks]]
room_id = 173551
enable_monitor = true
enable_recorder = true

[output]
path_template = "{roomid}/{roomid}_{year}{month}{day}-{hour}-{minute}-{second}"
filesize_limit = 0
duration_limit = 1200
out_dir = "./Videos"

[logging]
log_dir = "./logs/blrecLog"
console_log_level = "INFO"
backup_count = 30

[bili_api]
base_api_urls = [ "https://api.bilibili.com",]
base_live_api_urls = [ "https://api.live.bilibili.com",]
base_play_info_api_urls = [ "https://api.live.bilibili.com",]

[header]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
cookie = ""

[danmaku]
danmu_uname = false
record_gift_send = true
record_free_gifts = false
record_guard_buy = true
record_super_chat = true
save_raw_danmaku = true

[recorder]
stream_format = "flv"
recording_mode = "standard"
quality_number = 250
fmp4_stream_timeout = 10
read_timeout = 3
disconnection_timeout = 600
buffer_size = 32768
save_cover = false
cover_save_strategy = "dedup"

[postprocessing]
remux_to_mp4 = true
inject_extra_metadata = true
delete_source = "auto"

[space]
check_interval = 0
space_threshold = 10737418240
recycle_records = false

[email_notification]
began_message_type = "html"
began_message_title = ""
began_message_content = ""
ended_message_type = "html"
ended_message_title = ""
ended_message_content = ""
space_message_type = "html"
space_message_title = ""
space_message_content = ""
error_message_type = "html"
error_message_title = ""
error_message_content = ""
notify_began = true
notify_ended = true
notify_error = true
notify_space = true
enabled = false
src_addr = ""
dst_addr = ""
auth_code = ""
smtp_host = "smtp.163.com"
smtp_port = 465

[serverchan_notification]
began_message_type = "markdown"
began_message_title = ""
began_message_content = ""
ended_message_type = "markdown"
ended_message_title = ""
ended_message_content = ""
space_message_type = "markdown"
space_message_title = ""
space_message_content = ""
error_message_type = "markdown"
error_message_title = ""
error_message_content = ""
notify_began = true
notify_ended = true
notify_error = true
notify_space = true
enabled = false
sendkey = ""

[pushdeer_notification]
began_message_type = "markdown"
began_message_title = ""
began_message_content = ""
ended_message_type = "markdown"
ended_message_title = ""
ended_message_content = ""
space_message_type = "markdown"
space_message_title = ""
space_message_content = ""
error_message_type = "markdown"
error_message_title = ""
error_message_content = ""
notify_began = true
notify_ended = true
notify_error = true
notify_space = true
enabled = false
server = ""
pushkey = ""

[pushplus_notification]
began_message_type = "markdown"
began_message_title = ""
began_message_content = ""
ended_message_type = "markdown"
ended_message_title = ""
ended_message_content = ""
space_message_type = "markdown"
space_message_title = ""
space_message_content = ""
error_message_type = "markdown"
error_message_title = ""
error_message_content = ""
notify_began = true
notify_ended = true
notify_error = true
notify_space = true
enabled = false
token = ""
topic = ""

[telegram_notification]
began_message_type = "html"
began_message_title = ""
began_message_content = ""
ended_message_type = "html"
ended_message_title = ""
ended_message_content = ""
space_message_type = "html"
space_message_title = ""
space_message_content = ""
error_message_type = "html"
error_message_title = ""
error_message_content = ""
notify_began = true
notify_ended = true
notify_error = true
notify_space = true
enabled = false
token = ""
chatid = ""
server = ""

[bark_notification]
began_message_type = "markdown"
began_message_title = ""
began_message_content = ""
ended_message_type = "markdown"
ended_message_title = ""
ended_message_content = ""
space_message_type = "markdown"
space_message_title = ""
space_message_content = ""
error_message_type = "markdown"
error_message_title = ""
error_message_content = ""
notify_began = true
notify_ended = true
notify_error = true
notify_space = true
enabled = false
server = ""
pushkey = ""
