line: kodo
limit: 3
streamers:
  VIDEO_PATH:
    copyright: 1
    source: BILI_SOURCE
    tid: 138
    cover: 
    title: 【弹幕版】某某某直播回放-%Y年%M月%d日%H点场(按需修改)
    desc_format_id: 0
    desc: edit your video description(视频简介，按需修改)
    dynamic: ""
    tag: tag1,tag2,tag3(视频标签按需修改标签之间用英文逗号间隔)
    dtime: ~
